name: Add issues to Infracloud project board

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  addIssuesToProjectBoard:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run script to add issues to project board
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          chmod 755 addIssues2InfracloudProject.sh
          ./addIssues2InfracloudProject.sh
